export enum ValidationErrors {
  ICRORRECT_FIRSTNAME = 'ICRORRECT_FIRSTNAME',
  ICRORRECT_LASTTNAME = 'ICRORRECT_LASTTNAME',
  ICRORRECT_AGE = 'ICRORRECT_AGE',
  NO_DATA = 'NO_DATA',
  SERVER_ERROR = 'SERVER_ERROR',
};
