name: linting, testing, building
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Linting ts
        run: yarn lint:ts

      - name: Linting scss
        run: yarn style:scss

      - name: Testing
        run: yarn test:unit:ci

      - name: Build storybook
        run: yarn build-storybook

      - name: Testing ui
        run: yarn test:ui:ci

      - name: Build
        run: yarn build:prod
